services:
  rust:
    container_name: 'compute-instance.feed-parser'
    image: akitenkrad/compute-instance.cpu:latest
    user: root
    tty: true
    volumes:
      - ./:/workplace
      - data:/data
      - /Users/akitenkrad/.ssh:/root/.ssh
    environment:
      TZ: Asia/Tokyo
    working_dir: /workplace
    platform: linux/amd64
volumes:
  data:
    name: data
    external: true
