[tasks.test]
args = [
    "nextest",
    "run",
    "--workspace",
    "--status-level",
    "all",
    "--test-threads=1",
]
command = "cargo"
install_crate = { crate_name = "cargo-nextest", binary = "cargo", test_arg = [
    "nextest",
    "--help",
] }
